// Third-party notices. MIT, BSD and Apache-2.0 all ask that the copyright
// notice and licence text accompany a distribution, and shipping the PWA to a
// browser is one, so the app carries them here rather than relying on comments
// the minifier strips out. Apache-2.0 4(d) additionally requires a dependency's
// NOTICE file be reproduced, which is why those get their own block.
//
// Everything on this page comes from src/licenses.ts, generated by
// scripts/gen-licenses.mjs. Nothing here is hand-maintained.
import { Page } from './Page.js';
import { LICENSES, LICENSE_TEXTS, type LicenseEntry } from '../licenses.js';

/** Group packages under their licence, licences with most packages first. */
function groupBySpdx(entries: LicenseEntry[]): [string, LicenseEntry[]][] {
  const groups = new Map<string, LicenseEntry[]>();
  for (const e of entries) {
    const list = groups.get(e.spdx);
    if (list) list.push(e);
    else groups.set(e.spdx, [e]);
  }
  return [...groups.entries()].sort((a, b) => b[1].length - a[1].length || a[0].localeCompare(b[0]));
}

export function Licenses() {
  const groups = groupBySpdx(LICENSES);
  const notices = LICENSES.filter((e) => e.notice);

  return (
    <Page title="Open source licenses">
      <p className="fine-print">
        This app is built on {LICENSES.length} open source components. Their copyright notices and licence terms are
        reproduced below, in full. Our thanks to everyone who wrote them.
      </p>

      {groups.map(([spdx, pkgs]) => (
        <section className="about-section license-group" key={spdx}>
          <h2>{spdx}</h2>
          <ul className="license-list">
            {pkgs.map((p) => (
              <li key={p.name}>
                <span className="license-pkg">
                  {p.url ? <a href={p.url}>{p.name}</a> : p.name} <span className="search-meta">{p.version}</span>
                </span>
                {p.copyright && <span className="fine-print">{p.copyright}</span>}
                {p.note && <span className="fine-print">{p.note}</span>}
              </li>
            ))}
          </ul>
          {LICENSE_TEXTS[spdx] && (
            <details className="license-text">
              <summary>Full {spdx} licence text</summary>
              <pre>{LICENSE_TEXTS[spdx]}</pre>
            </details>
          )}
        </section>
      ))}

      {notices.length > 0 && (
        <section className="about-section">
          <h2>NOTICE files</h2>
          <p className="fine-print">
            Reproduced as required by section 4(d) of the Apache License, Version 2.0.
          </p>
          {notices.map((p) => (
            <details className="license-text" key={p.name}>
              <summary>{p.name}</summary>
              <pre>{p.notice}</pre>
            </details>
          ))}
        </section>
      )}
    </Page>
  );
}
